// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_3_nephi_20 from "./routes/3-nephi-20.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $charity from "./routes/charity.tsx";
import * as $dc_4 from "./routes/dc-4.tsx";
import * as $dc_5 from "./routes/dc-5.tsx";
import * as $dc_6 from "./routes/dc-6.tsx";
import * as $index from "./routes/index.tsx";
import * as $isaiah_2_14 from "./routes/isaiah-2-14.tsx";
import * as $isaiah_29 from "./routes/isaiah-29.tsx";
import * as $isaiah_48_49 from "./routes/isaiah-48-49.tsx";
import * as $isaiah_50_52 from "./routes/isaiah-50-52.tsx";
import * as $isaiah_53 from "./routes/isaiah-53.tsx";
import * as $isaiah_54 from "./routes/isaiah-54.tsx";
import * as $isaiah_aleppo_1_20 from "./routes/isaiah-aleppo-1-20.tsx";
import * as $isaiah_aleppo_21_40 from "./routes/isaiah-aleppo-21-40.tsx";
import * as $isaiah_aleppo_41_66 from "./routes/isaiah-aleppo-41-66.tsx";
import * as $joseph_smith_matthew from "./routes/joseph-smith-matthew.tsx";
import * as $malachi_3_4 from "./routes/malachi-3-4.tsx";
import * as $malachi_4 from "./routes/malachi-4.tsx";
import * as $mark_16 from "./routes/mark-16.tsx";
import * as $micah_5 from "./routes/micah-5.tsx";
import * as $om_1_nephi_chapter_1 from "./routes/om-1-nephi-chapter-1.tsx";
import * as $om_1_nephi_chapter_2 from "./routes/om-1-nephi-chapter-2.tsx";
import * as $om_1_nephi_chapter_3 from "./routes/om-1-nephi-chapter-3.tsx";
import * as $om_1_nephi_chapter_4 from "./routes/om-1-nephi-chapter-4.tsx";
import * as $om_1_nephi_chapter_5 from "./routes/om-1-nephi-chapter-5.tsx";
import * as $om_1_nephi_chapter_6 from "./routes/om-1-nephi-chapter-6.tsx";
import * as $om_1_nephi_chapter_7 from "./routes/om-1-nephi-chapter-7.tsx";
import * as $om_2_nephi_chapter_1 from "./routes/om-2-nephi-chapter-1.tsx";
import * as $sermon_on_the_mount from "./routes/sermon-on-the-mount.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $Offline from "./islands/Offline.tsx";
import * as $Picture from "./islands/Picture.tsx";
import * as $WordMatchEventListener from "./islands/WordMatchEventListener.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/3-nephi-20.tsx": $_3_nephi_20,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/charity.tsx": $charity,
    "./routes/dc-4.tsx": $dc_4,
    "./routes/dc-5.tsx": $dc_5,
    "./routes/dc-6.tsx": $dc_6,
    "./routes/index.tsx": $index,
    "./routes/isaiah-2-14.tsx": $isaiah_2_14,
    "./routes/isaiah-29.tsx": $isaiah_29,
    "./routes/isaiah-48-49.tsx": $isaiah_48_49,
    "./routes/isaiah-50-52.tsx": $isaiah_50_52,
    "./routes/isaiah-53.tsx": $isaiah_53,
    "./routes/isaiah-54.tsx": $isaiah_54,
    "./routes/isaiah-aleppo-1-20.tsx": $isaiah_aleppo_1_20,
    "./routes/isaiah-aleppo-21-40.tsx": $isaiah_aleppo_21_40,
    "./routes/isaiah-aleppo-41-66.tsx": $isaiah_aleppo_41_66,
    "./routes/joseph-smith-matthew.tsx": $joseph_smith_matthew,
    "./routes/malachi-3-4.tsx": $malachi_3_4,
    "./routes/malachi-4.tsx": $malachi_4,
    "./routes/mark-16.tsx": $mark_16,
    "./routes/micah-5.tsx": $micah_5,
    "./routes/om-1-nephi-chapter-1.tsx": $om_1_nephi_chapter_1,
    "./routes/om-1-nephi-chapter-2.tsx": $om_1_nephi_chapter_2,
    "./routes/om-1-nephi-chapter-3.tsx": $om_1_nephi_chapter_3,
    "./routes/om-1-nephi-chapter-4.tsx": $om_1_nephi_chapter_4,
    "./routes/om-1-nephi-chapter-5.tsx": $om_1_nephi_chapter_5,
    "./routes/om-1-nephi-chapter-6.tsx": $om_1_nephi_chapter_6,
    "./routes/om-1-nephi-chapter-7.tsx": $om_1_nephi_chapter_7,
    "./routes/om-2-nephi-chapter-1.tsx": $om_2_nephi_chapter_1,
    "./routes/sermon-on-the-mount.tsx": $sermon_on_the_mount,
  },
  islands: {
    "./islands/Header.tsx": $Header,
    "./islands/Offline.tsx": $Offline,
    "./islands/Picture.tsx": $Picture,
    "./islands/WordMatchEventListener.tsx": $WordMatchEventListener,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
